spring:
  datasource:
    url: jdbc:h2:mem:order_service_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS order_service_db
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
  flyway:
    locations: "classpath:/db/migration"

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://zipkin.team-a.cloud.school.thoughtworks.cn

  cloud:
    stream:
      bindings:
        outputOrder:
          destination: order
          group: default
          content-type: application/json


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework.web: DEBUG

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
